org: lautarogra
app: puppeteer
service: aws-lambda-puppeteer-serverless

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x

functions:
  puppeteerExample:
    handler: run_puppeteer.handler
    timeout: 800
    events:
      - schedule: rate(10 minutes)
    url: true
